@extends('layouts.page')
@section('title', "Our terms and conditions for mycustomessays")
@section('meta')
<meta name="description"content="Are you looking for affordable custom essay? place order now and get free plagiarism paper  "/>
<meta name="title" content="Terms And Conditions of mycustomessays"/>
<link rel="canonical" href=" https://mycustomessays.com/terms-and-conditions" />
<meta name="twitter:card" content="Summary" />
<meta name="robots" content="follow, index "/>
<meta name="twitter:url" content="https://mycustomessays.com/terms-and-conditions"/>
<meta property="article:published_time" content=" "/>
<meta property="article_updated_time" content=" "/>
<meta property="og:locale" content="en_US"/>
<meta property="og:type" content="Website"/>

@endsection



@section('page')
<section class=" py-5 service-bg">
     
        <div class="container">
        		<h1 class="text-center">Terms and Conditions</h1></div>
        		</section>

    <section class=" py-5 ">
     
        <div class="container">
        		
            <div class="row">
                <div class="col-md-12">
               <h2> 1. Vocabulary</h2>
1.1. ‘Agreement’ refers to these Terms and Conditions.<br>
1.2. ‘Company’ means the entity that provides independent research and writing services to Customers according to the defined terms laid out in this Agreement.<br>
1.3. ‘Writer’ is the person, who has agreed to work with the Company on a freelance basis to provide research and writing services under the Company's terms.<br>
1.4. ‘Customer’ is the person who places an Order with the Company to obtain the Product according to his or her requirements and governed by the defined terms and conditions laid out in this Agreement.<br>
1.5. ‘Order’ is an electronic request of a paid service from the Customer for a particular Product and/or service.
1.6. ‘Order Status’ defines order progress on a particular stage.<br>
1.7. ‘Product’ is a document in an electronic format that is the final result of Order completion.<br>
1.8. ‘Product Revision’ is an edited version of the original Product initialized by Customer.<br>
1.9. ‘Support Team or Support’ is the part of the Company’s organizational structure with the mission to assist and coordinate the Order process.<br>
1.10. ‘Quality Assurance Department’ signifies the part of the Company’s organizational structure with the mission to guard and evaluate the quality of Product and service provided.<br>
1.11. ‘Messaging System’ is an interactive feature that ensures communication between the Customer and Support/Writer.<br>
1.12. ‘Verification Process’ is a procedure required from the Customer in order to confirm his/her billing identity to prevent fraud.<br>
1.13. ‘Store Credit’ is the customer’s money account within the Company.<br>
<h2>2. Privacy Policy</h2>
2.1. The Company is committed to protect the privacy of the Customer and it will never resell or share any of the Customer’s personal information, including credit card data, with any third party. The company does its best to save the Customer from the risk of having their credit card data disclosed. The Company, however, does not fully guarantee any credit card data disclosures that may occur beyond its control and/or without its fault.<br>
2.2. Certain pages on the Company’s web site require the Customer to provide their name, e-mail address, home address or phone number ( for example, when filling in the order-form). The Company does not use this information for any other purpose other than verification and to contact the Customer with regards to the Order. All additional files provided by the Customer in order to pass the Verification Process are deleted from the Company’s database right after verification is completed.<br>
2.3. Direct contact between the Customer and the Writer is prohibited to keep the personal information of the Customer safe and confidential. The Customer is welcome to use the numerous interactive features created by the Company for that purpose and a qualified Support Team is available for the Customer 24/7.<br>
2.4. Information provided by the Customer in Order description and in additional files needed for Order completion immediately becomes visible for the Writers once Order is paid. The Company is not responsible for the information voluntarily disclosed by the Customer when placing an Order and highly encourages the Customer to avoid including any personal or billing information (i.e. Customer’s phone number, email address etc.) as well as disclosing the Customer’s identity when communicating with the Writer through the Messaging System.<br>
<h2>3. Nature of Product and Terms of Usage</h2>
3.1. The Company offers a service that locates suitably qualified experts for the provision of independent personalized research and writing services provided to the Customer as a unique reference that is designed to assist in the completion of the Customer’s assignments or academic obligations. Therefore, it is understood that the Company does not make any guarantees regarding Customer’s grades as an outcome or consequence of submission of the Product to any academic institution. The purpose of this Agreement is strictly to provide the Customer with an original reference document or related services according to the Customer’s instructions. Everything provided by the Company is intended for research/reference purposes only. The Company is also not responsible for failure on the part of the Customer to learn the material covered by the Product or improper usage of research contained therein.<br>
3.2. Intellectual property is owned by the Company and the Customer has the exclusive permission and right to use the Product for a limited period of six (6) months. When the six (6) months period has passed, the Company shall exclusively regain all rights of the Product.<br>
<h2>4. Order Process</h2>
4.1. Placing an Order. When filling in an Order form, it is the sole responsibility of the Customer to register using a valid email address and to provide a correct phone number where the Customer can be reached (preferably both - home and mobile). There may be multiple occasions during Order preparation when establishing contact with the Customer is crucial. Failure to provide a valid email address or a correct phone number may affect Order completion and will result in a violation of the terms and conditions of this Agreement. This may lead to forfeiture of any claim to the implied warranty or guarantee by the Customer.<br>
The Company cannot begin working on the Customer's Order until the Customer has paid for the entire amount of the Product(s) and/or service(s). The Company is not liable or responsible for the failure of a Customer to pay on time. The Customer must be precise and attentive when filling in the Order form. The Company's 5%, 10% and 15% membership discounts are not applied for papers that involve multiple choice questions, both time-framed and non-time-framed. For each order placed at multiple choice questions, the Customer gets a discount according to the number of the ordered questions. The Customer can also use a discount to lessen the price if the Customer is entitled to it. Special offers or discounts on the Company's Products and services may not be used together at the same time and cannot be combined with any additional services.<br>
4.2. Instructions. Because the Company works based on Customer’s instructions, these instructions must be clear and precise. If the instructions are not clear and additional instructions are needed to complete the Order, but are not provided within the required time schedule, the Company cannot fulfill any implied warranty or guarantee and it shall not be held responsible. The Customer is advised that once the Order is completed any revision request must only be based on the initial requirements and description of the original Order. Any changes from the initial instructions of the Order will be considered "editing". This is an additional service and the Company will not conduct any free revision request that is different or deviates from the original Order requirements and/or description. Instructions and additional requests must be sent before a Writer is assigned to the Customer’s Order. Failure to meet this requirement will result in a violation of this Agreement and forfeiture of any claim to the implied warranty or guarantee.<br>
4.3. Sources. The Writer is allowed to use any relevant source available for the completion of the requested assignment - books, journals, newspapers, interviews, online publications etc., unless the Customer mentions some particular sources to be used or others to be ignored. If the Customer needs specific sources that are crucial for the completion of the Order, the Company would expect the Customer to provide them within the required time schedule listed below.<br>
48 hours - 10 days: Instructions and all sources must be received within the first 8 hours.<br>
12 hours - 24 hours: Instructions and all sources must be received within the first 1 hour.<br>
12 hours - or less: Instructions and all sources must be received within the first 20 minutes.<br>
Failure to do so will result in a violation of the terms and conditions of this Agreement and forfeiture of any claim to the implied warranty or guarantee.<br>
4.4. Matching of the Academic Level. In the event that the desired academic level chosen by the Customer is the improper academic/quality level (either by accident or not), the Customer shall assume all liability for such error. It shall be the Customer’s sole responsibility to choose the correct academic level that best fits the required assignment at the time of making the Order. If the Customer has made an error while placing an Order, then the Customer must contact the Support Team immediately for assistance.<br>
4.5. Checking the Messaging System. The Messaging System is an easy and convenient way to communicate. The Customer should check messages for any updates from the Support Team or from the Writer. The Customer should also promptly address any questions, concerns or give additional instructions using this interactive feature. Failure or neglect to check the Messaging System shall not be sufficient ground for a refund of services rendered. If the Customer does not know how to use the Messaging System, the Customer may contact the Support Team at any time for assistance or instructions.<br>
4.6. Incorrect Order Placement. The Company reserves the right not to process or to resubmit the Customer’s Order in the event that the details indicated are inconsistent to or do not match the Order's original description. Failure to provide the correct description or choosing the wrong Product, deadline extension requests or Writer level upgrade may require additional payments. Please note this is done by the Company only so that it may properly process the Customer’s Order and have the best possible Writer to complete the Customer’s Order. The Customer will always be contacted to approve any additional charges or requests.<br>
4.7. Tracking Order Progress. The Customer is highly encouraged to stay in touch with the Support Team/Writer and to monitor Order Progress through the Customer’s personal account on the web site. The possible statuses of the order are:<br>
Order is not paid – albeit the Order is registered within the Company’s system, the Customer should proceed with the payment first for the Company to start working on it.<br>
Research has been started – Order is successfully paid and available for the Writers of the chosen level.
Preparing – a Writer has been assigned to work on the Order.<br>
Order is completed. Download – the Product has been uploaded for the Customer’s review. The Customer is welcome to download it from the Customer’s personal account on the web site.<br>
Order is returned for revision – Writer is revising the Product according to Customer’s instructions.<br>
Hold – the Order is put on hold by the Support Team and the Writer has temporarily stopped working on it. The Customer is advised to visit Messaging board on the personal profile for detailed information or to contact the Support Team.<br>
Canceled – the Order is canceled.<br>
4.8. Client can request for a draft from Writer, however, the Company does not guarantee a draft if Order's urgency is 3-48 hours.<br>
<h2>5. Delivery/Downloading Policy</h2>
4.9. Preferred Writer. When placing an Order, the Customer can indicate a preferred Writer to be assigned to an Order. The Company reserves the right to decline a preferred Writer request based on a Writer's history, recent quality and lateness issues that might jeopardize Order completion. The Company will inform the Customer about its decision and provide supporting materials. If the Customer insists on his/her chosen Writer, the Company will not be responsible for failure of the preferred Writer to deliver a high quality Product in a timely manner. No refund can be guaranteed at that point.<br>
5.1. The Company strives for the highest level of satisfaction available. However, the Company cannot and will not be held liable or responsible for any type of delivery issues resulting from problems such as spam filters, incorrect email, lack of internet access or general neglect, among others, which are beyond its control and/or without its fault. The Support Team is available 24 hours a day to assist the Customer with any delivery problems of the Order. The Company will do its best to meet the Customer’s academic writing needs by maintaining up-to-date software. However, it is the sole responsibility of the Customer to provide the correct contact information to the Company.<br>
5.2. In case of timely delivery of the Product, the Company will not be responsible for failure of the Customer to download the Product. Please note that the Customer will still be billed for the service rendered and no refund is guaranteed at this point in order to pay the Writer for the work done.<br>
<h2>6. Verification Process</h2>
6.1. Protecting billing information of the Customers and eliminating fraud is a priority that the Company takes seriously. The Company is obliged by authorities along with merchant providers and banks to protect the credit card holders who purchase from it. Accordingly, due to the nature of the Company’s business, type of Product and the fact that it is delivered by electronic means, no hand written signature is required as proof of delivery.<br><br>
6.2. The Company reserves the right to request the Customer to provide:<br><br>
- photo-copy of Customer’s credit card (the digits or numbers may be covered except the last 4)<br><br>
- photo-copy of Customer’s Passport (or visa copy for international students)<br><br>
- photo-copy of Customer’s official ID (Driver's License or other government issued ID)<br><br>
- authorization code from Customer’s bank.<br><br>
The aforementioned documents may be made by scanner, digital camera or cell phone with camera. Everything provided by the Customer in order to pass the Verification Process is never shared to any third parties. The copies that are requested are not used for any other purpose but only to verify the Customer’s identity. For the Customer’s security the Company does not store files and documents that are sent for verification. These are immediately trashed once Verification is completed.<br><br>
6.3. When requested to verify the Customer’s billing information, it is the Customer’s sole responsibility to comply immediately to ensure that the billing information meets the Company’s anti-fraud policies and procedures. Any verification requests must be completed in the following time schedule. <br>
If the Order is requested to be delivered between 48 hours and 10 days the Customer’s billing information must be verified within the first 8 hours to comply with any implied warranty or guarantee.<br>
If the Customer’s urgency level is within 12-24 hours the Customer’s billing information must be verified within the first 1 hour to comply with any implied warranty or guarantee.<br>
If the Customer’s urgency level is less than 12 hours the Customer’s billing information must be verified within the first 20 min to comply with any implied warranty or guarantee.<br>
Failure on the part of the Customer to do so will result in a violation of the terms and conditions of this Agreement and forfeiture of any claim to the implied warranty or guarantee.<br>
6.4. Any unauthorized use of a stolen credit card is prohibited by law and will be reported to the applicable law enforcement agencies for further investigation. The Company works closely with the authorities to fight cyber crime and report all fraudulent Orders for prosecution.<br>
<h2>7. Termination</h2>
7.1. The Company reserves the right to cancel any paid Order at its own determination or decision in case there is lack of cooperation/communication from the Customer’s side that affects Order completion or a suspicion by the Company that the Customer is engaged in a fraudulent activity. The Company does not guarantee reimbursement in the circumstances described above. Each case is analyzed separately and final decision depends on the number of factors. The Company shall have sole discretion to take action based on the particular circumstances of each case.<br>
<h2>8. Revision policy</h2>
8.1. The Free Revision policy is a courtesy service that the Company provides to help ensure Customer’s total satisfaction with the completed Order. To receive free revision the Company requires that the Customer provide the request within fourteen (14) days from the first completion date of the Order/Product and within a period of thirty (30) days for any dissertation, thesis, research proposal, thesis proposal, dissertation chapters writing or any other reasonably large assignments. If the Customer has missed the policy deadline, the Customer may choose to have the order revised but for additional payment or the Customer may place a new one for editing.<br>
8.2. Quality Assurance Department of the Company reserves the right to limit the number of revisions or decline revision requests in cases such as, but not limited to: changes in initial order details; unreasonable return of the assignment; taking advantage of Writer and obvious abuse of revision option.<br>
8.3. If revision request violates original instructions, the Quality Assurance Department has the right to decline it. If request falls within mentioned guidelines, the Company will happily revise the Customer’s Order to meet the initial requirements free of charge.<br>
<h2>9. Satisfaction Guarantee</h2>
9.1. The Product ordered is guaranteed to be original and delivered in a timely manner. Orders are checked by the most advanced anti-plagiarism software in the market to assure that the Product is 100% original. The Company has a zero tolerance policy against plagiarism.<br>
9.2. The Company does not and cannot guarantee that editing, proofreading, formatting services will be plagiarism free. Papers and other materials that are not written or made by the Company will not be scanned or reviewed for possible incidence of plagiarism. The Company shall not refund any amount in the event that a proofread/formatted paper or Product is considered to be plagiarized.<br>
9. 3. If the Customer needs to cancel an Order, it may be made at any time prior to the completion of the Order.<br>
9.4. All refunds and cancellations should be communicated and expressed in writing by using the Order Messaging System or by e-mailing the Support Team. In the unlikely event that the Customer is not satisfied with the Product or receive the Product after the specified deadline, the Customer may request a partial or full refund. It is the sole discretion of the Company to approve or disapprove any request on an individual case to case basis.<br>
9.5. In case of a refund request due to bad quality of the Product, the Customer must provide strong reasons, and examples to back up the claim for refund. Only after an extended list of violations is provided, will the request for refund be forwarded to the Quality Assurance Department for further investigation and refund request approval. Please note that the Company can also ask for additional materials or evidence to support the request. Quality Assurance Department reserves the right to decline refund inquiry if aforementioned information or documents are not provided when the request is made.<br>
9.6. If the refund request is not received within seventy-two (72) hours after Order completion it is to be assumed that the Customer is satisfied with the Product and the Customer will not be eligible for any refunded amount.<br>
9.7. In case a full refund is issued or Order becomes unpaid in circumstances where the service rendered has already been delivered, the Writer retains full authorship for the Product completed and reserves the right to use, resell, distribute and share it to other third parties. The Customer is then not eligible to use the Product for whatever purpose.<br>
9.8. The Company shall not be responsible for failure of the Customer to learn the material covered by the Product or for improper usage of research contained therein and no refund shall be made by the Company in case the Customer receives a failing grade. For more details see section 2.1.<br>
9.9. Store Credits accepted by the Customer as a compensation for any occurred inconveniences are non-refundable.
9.10. The Company reserves the right to contact the Customers by email regarding new services, discounts, special offers and any other information that the Company may deem useful for the Customers.<br>
9.11. Short Message Service (SMS) Alerts allow the Customers to receive alerts on their mobile phones in the form of a SMS text message. By placing an Order, the Customer agrees to receive mobile phone alerts and updates from the Company. The Company also reserves the right to alter or modify any SMS Alerts at any time without further notice to the Customer which may include special offers and discounts. The Company will not be responsible for any additional charges for the Company SMS Alerts that may be charged against the Customer by the mobile service provider.
<h2>10. Waiver of Breach</h2>
10.1. No waiver by the Company of any breach of this Agreement by the Customer shall be held to be a waiver of any other or subsequent breach. All remedies afforded in this Agreement shall be taken and construed as cumulative, that is, in addition to every other remedy provided herein or by law.<br>
10.2. The failure of the Company to insist on a strict performance of any of the terms and conditions of this Agreement shall be deemed a waiver of the rights or remedies that the Company may have regarding that specific instance only, and shall not be deemed a waiver of any subsequent breach of default in any terms and conditions.
<h2>11. Amendments</h2>
11. 1. The Company reserves the right to modify, amend, revise or otherwise change any and all provisions of this Agreement. The Customer expressly agrees to be bound by any subsequent modification, amendment, revision or changes as contemplated herein, by the continued rendition of services by the Company. It shall be the obligation of the Customer to review this Agreement for changes from time to time, since any changes are reflected in this section of the website.<br>
<h2>12. Miscellaneous Provisions</h2>
12.1. Entire Agreement - This Agreement contains the entire stipulations between the Customer and the Company, and no statements, promises, or inducements made by either party or agent of either party that are inconsistent herein shall be valid or binding, unless expressly authorized under this Agreement. This Agreement may not be enlarged, modified, or altered except in writing signed by the parties and indorsed on this Agreement. This Agreement shall supersede all previous communications, representations, or agreements, either verbal or written, between the Customer and the Company.<br>
12.2. Severability - It is understood and agreed by the Customer that if any part, term, or provision of this Agreement is held by the courts to be illegal or in conflict with any law of the state where made, the validity of the remaining portions or provisions shall not be affected, and the rights and obligations of the Customer shall be construed and enforced as if the Agreement did not contain the particular part, term, or provision held to be invalid.<br>
12.3. Law Governing - It is mutually understood and agreed that this Agreement shall be governed by the laws of the place where the Company holds its principal place of business, both as to interpretation and performance, or in any other place at the determination of the Company.<br>
12.4. Place of Suit - Any action or other judicial proceeding for the enforcement of this Agreement or any of its provisions shall be instituted in the courts of competent jurisdiction in the place where the Company holds its principal place of business or in any other place at the determination of the Company.<br>


                </div>
            </div>
        </div>
    </section>
@endsection